### ISSUE TITLE
JDK-8211399:  libxslt fails to build with glibc 2.26

### ISSUE THREAD

**Issue by ebourg** [javafxports/openjdk-jfx#234]
OpenJFX 11+26 fails to build on Debian sid with the following error:

```
In file included from ./modules/javafx.web/src/main/native/Source/ThirdParty/libxslt/src/libxslt/xsltInternals.h:24,
                 from ./modules/javafx.web/src/main/native/Source/ThirdParty/libxslt/src/libxslt/attributes.c:43:
./modules/javafx.web/src/main/native/Source/ThirdParty/libxslt/src/libxslt/xsltlocale.h:29:10: fatal error: xlocale.h: No such file or directory
 #include <xlocale.h>
          ^~~~~~~~~~~
compilation terminated.
```

It seems this is caused by the removal of xlocale.h in glibc 2.26. Debian sid has the version 2.27.

Removing the include in xsltlocale.h solves the issue.

**Comment by johanvos** [comment]
I notice the include is wrapped in an
```
#ifdef HAVE_XLOCALE_H
#include <xlocale.h>
#endif
```

where `HAVE_XLOCALE_H` is unconditionally set to 1 in modules/javafx.web/src/main/native/Source/ThirdParty/libxslt/linux/config.h 

Maybe we can check on glibc_2.26 in config.h, and based on that set `HAVE_XLOCALE_H` ?

**Comment by kevinrushforth** [comment]
@ararunprasad can probably comment as to whether xlocale.h is needed at all and how it is used.

**Comment by johanvos** [comment]
openjdk bugs id:  https://bugs.openjdk.java.net/browse/JDK-8211399

**Comment by ararunprasad** [comment]
The reason for this issue is we don't run `configure` on each build.

I see that other projects also had faced similar issue, PSB

https://github.com/agracio/electron-edge-js/issues/16
https://github.com/facebook/hhvm/issues/8009
https://github.com/meta-toolkit/meta/issues/195

So the recommended solution is to use `locale.h` instead of `xlocale.h`.

diff -r 50a317077b4c modules/javafx.web/src/main/native/Source/ThirdParty/libxslt/linux/config.h
--- a/modules/javafx.web/src/main/native/Source/ThirdParty/libxslt/linux/config.h       Fri Sep 28 17:31:56 2018 +0530
+++ b/modules/javafx.web/src/main/native/Source/ThirdParty/libxslt/linux/config.h       Wed Oct 03 11:48:31 2018 +0530
@@ -143,7 +143,7 @@
 #define HAVE_VSPRINTF 1

 /* Define to 1 if you have the <xlocale.h> header file. */
-#define HAVE_XLOCALE_H 1
+/* #undef HAVE_XLOCALE_H 1 */

 /* Define to 1 if you have the `_stat' function. */
 /* #undef HAVE__STAT */

**Comment by ararunprasad** [comment]
https://github.com/javafxports/openjdk-jfx/pull/314

**Comment by kevinrushforth** [comment]
Fixed by [JDK-8211399](https://bugs.openjdk.java.net/browse/JDK-8211399).
